<a href="https://colab.research.google.com/github/BoshiLee/pytorch_learning/blob/main/dimensional_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch

In [5]:
import torch

建立一維陣列

In [8]:
one_d = torch.arange(1, 5)
one_d

tensor([1, 2, 3, 4])

建立 1 ~ 100 間隔為 3 的一維陣列

In [15]:
one_d_gap_three = torch.arange(1, 100, 3)
one_d_gap_three

tensor([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52,
        55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

可以發現建立時不會包含地二個餐數 100

建立二維陣列

In [19]:
two_d = one_d_gap_three.view(11, 3)
print(two_d)

tensor([[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25],
        [28, 31, 34],
        [37, 40, 43],
        [46, 49, 52],
        [55, 58, 61],
        [64, 67, 70],
        [73, 76, 79],
        [82, 85, 88],
        [91, 94, 97]])


印出陣列的維度

In [21]:
print(two_d.dim())

2


取得 2 維陣列元素

In [22]:
print(two_d[0, 2])

tensor(7)


建立其他維度的陣列

In [25]:
torch.arange(1, 51).view(2, 5, 5)

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25]],

        [[26, 27, 28, 29, 30],
         [31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40],
         [41, 42, 43, 44, 45],
         [46, 47, 48, 49, 50]]])