<a href="https://colab.research.google.com/github/BoshiLee/pytorch_learning/blob/main/linear_regression_create_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install torch

In [2]:
import torch
from torch.nn import Linear

In [3]:
torch.manual_seed(0)
model = Linear(in_features=1, out_features=1) # 建立線性 model 輸入變數 1 個 輸出也 1 個
print(model.weight, model.bias)

Parameter containing:
tensor([[-0.0075]], requires_grad=True) Parameter containing:
tensor([0.5364], requires_grad=True)


Prediction

In [5]:
x = torch.tensor([[2.0], [3.0]])
print(model(x))

tensor([[0.5215],
        [0.5140]], grad_fn=<AddmmBackward0>)
