<a href="https://colab.research.google.com/github/BoshiLee/pytorch_learning/blob/main/pytorch_crash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install torch

In [ ]:
import torch
import numpy as np

In [ ]:
v = torch.tensor([1, 2, 3, 4, 5, 6])
print(v[1: 5])

tensor([2, 3, 4, 5])


In [ ]:
f = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
print(f.dtype)

torch.int64


view: 將矩陣重製

In [ ]:
v.view(6, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
newV = v.view(2, 3)
print(newV)
newV.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [ ]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


轉換 numpy array 到 tensor array

In [ ]:
tensorCnv = torch.from_numpy(a)
print(tensorCnv)

tensor([1, 2, 3])


轉換 tensor array 到 numpy array

In [ ]:
numpyCnv = tensorCnv.numpy()
print(numpyCnv)

[1 2 3]
